### ISSUE TITLE
RangeSelector: Click functionality

### ISSUE THREAD

**Issue by tumentumurchudur** [mxenabled/mx-react-components#113]
Can we allow users to click somewhere on the range line and be able to move the slider to the clicked point without having to drag it?  The slider in jQuery works that way.

<img width="1259" alt="screen shot 2015-11-18 at 4 19 12 pm" src="https://cloud.githubusercontent.com/assets/9920303/11257684/77c4fb88-8e10-11e5-8378-5e071dc2b52e.png">

**Comment by bsbeeks** [comment]
I don't see why not. But, how would we know which toggle to move?

**Comment by tumentumurchudur** [comment]
Actually, there are three scenarios where the user can click on the range line. 
- Anywhere on the left side of the left slider - Move the left slider to the clicked position
- Anywhere on the right side of the right slider - Move the right slider to the clicked position
- Between the two sliders - (Suggestion) Move whichever the slider is closest to the clicked position

**Comment by bsbeeks** [comment]
I like it. This isn't a pressing feature to add, so let's work on it when we have time. Or maybe someone outside of MX would like to take a stab at it.

**Comment by lukeschunk** [comment]
I'd like to take a stab at this - If that sounds good I could likely be ready to submit a PR by the end of this week.

**Comment by bsbeeks** [comment]
@lukeschunk sounds great!

**Comment by lukeschunk** [comment]
@bsbeeks great I just submitted a PR - took me a few times to get the travis ci build to pass! I really enjoyed working on this - let me know if your team notices any changes otherwise I can work on another issue soon
