### ISSUE TITLE
Convert components back to using createClass instead of ES6 classes

### ISSUE THREAD

**Issue by bsbeeks** [mxenabled/mx-react-components#142]
We are currently using `createClass` in all of our internal projects at MX. Jumping between the 2 syntaxes is a bit confusing...especially for newbies. For not let's move everything back to `createClass` until we convert our internal projects to ES6.

**Comment by lukeschunk** [comment]
I can work on this once the craziness of this week is over for me. I'll check the docs, but when we make that change, we move all the default prop types and validation inside of the class, right?

**Comment by jmophoto** [comment]
Components to be converted
- [ ] DatePicker
- [ ] DatePickerFullScreen
- [ ] DonutChart
- [ ] Icon
- [ ] Loader
- [ ] Modal
- [ ] RajaIcon
- [ ] RangeSelector
- [ ] Select
- [ ] SelectFullScreen
- [ ] Spin
- [ ] TimeBasedLineChart
- [ ] ToggleSwitch
- [ ] TypeAhead

**Comment by cerinman** [comment]
I'm revamping the `TimeBasedLineChart` component now so I can handle that one with the large changes that I'm already making.

**Comment by iheartrachie** [comment]
Can this be closed? I think we're reverted everything.

**Comment by cerinman** [comment]
Yes. This appears to be done.
