### ISSUE TITLE
Serif Font On Loader Text

### ISSUE THREAD

**Issue by lukeschunk** [mxenabled/mx-react-components#165]
I'm not sure if this is a real issue, but I was running the demo today for the components and I noticed that the loader text is a serif font. I looked at the code: `<div className='mx-loader-text' style={styles.text} > {this.props.children} </div>` and it seems to me like it should be getting the right font. When I inspected the element though there seemed to be no font applied to the element. 

Maybe it changed and I didn't realize it when I changed the loader text to allow for custom text?
<img width="1204" alt="screen shot 2016-01-29 at 9 58 58 am" src="https://cloud.githubusercontent.com/assets/13579578/12680348/f74509ca-c66e-11e5-816f-3aae40eade76.png">

**Comment by lukeschunk** [comment]
or has this always been a serif intentionally?

**Comment by bsbeeks** [comment]
@lukeschunk we are aware of the font issue. See https://github.com/mxenabled/mx-react-components/issues/147.

**Comment by lukeschunk** [comment]
sounds good!
