### ISSUE TITLE
New Button Style / Combo Button (button group with dropdown)

### ISSUE THREAD

**Issue by derek-boman** [mxenabled/mx-react-components#184]
#### Overview

Not sure the best way to implement this but wanted to open the discussion. Currently in Insight we have Button Groups like those shown below. This is a pattern I can see us using a lot in new widgets designs. (1) Does it make sense to standardize/componentize they way this is implemented? 

<img width="463" alt="screen shot 2016-02-01 at 10 17 26 am" src="https://git.moneydesktop.com/github-enterprise-assets/0000/0152/0000/8033/00e071ee-c8cd-11e5-9402-1a472fa6b6d0.png">

(2) One variation of how I see this being used is when one action catches 90% of use cases and other possible actions are used less often. In this case the primary action is always presented while other options are accessible via a dropdown (triggered from the second button in the group).

Example: Mailchimp
![screen shot 2016-02-01 at 10 24 00 am](https://git.moneydesktop.com/github-enterprise-assets/0000/0152/0000/8035/f1fdc5cc-c8cd-11e5-9c8f-15aa84fc3c72.png)

Example: Google Calendar
<img width="510" alt="screen shot 2016-02-01 at 10 24 56 am" src="https://git.moneydesktop.com/github-enterprise-assets/0000/0152/0000/8036/12b35c64-c8ce-11e5-8561-aeab06de91d2.png">

Mockup Example: Cash Flow 
![screen shot 2016-02-01 at 10 39 02 am](https://git.moneydesktop.com/github-enterprise-assets/0000/0152/0000/8039/10c9e042-c8d0-11e5-829c-7981f66b9bea.png)

I'll open a related issue for a simple dropdown menu component that I think we'll also use frequently.

@bsbeeks thoughts from you or your team?

**Comment by iheartrachie** [comment]
I'm going to take a stab at the Button Group. @derek-boman, I'm assuming that all the buttons will need to be the same type?

**Comment by derek-boman** [comment]
@iheartrachie: not sure what you mean by the_ same type_. If you're asking if you can have a button group with a secondary button on the left and a primary button on the right, the answer is no. They need to all be the same.

**Comment by iheartrachie** [comment]
@derek-boman I got the `primaryOutline` type working, moving to `base` now. Should `neutral` buttons be outlined in a similar fashion on hover?

**Comment by derek-boman** [comment]
`neutral` and `base` need some styling work. the new guidelines are in the style guide. See `buttons` page: https://app.frontify.com/d/KHQZnlj1XMIO/web-patterns

**Comment by derek-boman** [comment]
@iheartrachie has addressed half of this issue in the PR preferences above. The other half is in this issue: #185

**Comment by iheartrachie** [comment]
I'll take the second of this (the dropdown) because I want to use it somewhere.

**Comment by iheartrachie** [comment]
The second half of this is being addressed in #185 so I'm going to close this issue.
