### ISSUE TITLE
MX components / Select menus

### ISSUE THREAD

**Issue by derek-boman** [mxenabled/mx-react-components#185]
![image](https://git.moneydesktop.com/github-enterprise-assets/0000/0152/0000/8040/c6f477e2-c8d0-11e5-837b-86829f37e6a7.png)

We have this standard Select menu, which is good, i believe we'll need another type of Simple dropdown like the settings icon in top right of Insight/Target. The trigger for this menu would vary, sometimes as a Base Button, sometimes as an icon, etc. The menu itself would follow an established pattern (although there are probably use cases for both right and left aligned menus).

LMK any thoughts here. I have a few places to implement this right away.

![screen shot 2016-02-01 at 10 53 17 am](https://git.moneydesktop.com/github-enterprise-assets/0000/0152/0000/8044/168cfc10-c8d2-11e5-9bf1-a8fe9d18a27f.png)

Thoughts from @bsbeeks: I think we should adjust the existing Select element to not have a pre formatted trigger. We should let the user decide what the trigger is and how it looks. If we have a specific style that we reuse in a project, then we can create a project specific component that wraps the Select and defines a shared trigger style.

**Comment by lukeschunk** [comment]
a trigger meaning you can pass down via props what you want the main thing to be (text, an icon, jsx, etc) ?

**Comment by bsbeeks** [comment]
@lukeschunk the trigger meaning the element you click to show the options.

**Comment by lukeschunk** [comment]
I was just playing with this and I believe we already have this ability. We can change the name of the `placeholder` prop to something like `trigger` if that implies more versatility. 

You can see below I passed in an `<Icon size={25} type='apple' />` for this prop and i believe it's the desired functionality?

![select_trigger_gif](https://cloud.githubusercontent.com/assets/13579578/14127051/649a6eba-f5d2-11e5-807e-641b3539d82d.gif)

**Comment by lukeschunk** [comment]
I finally understand what Beeks means by this - I'm working on it for mobile to fix a Ranger bug and then I will work on it here.

**Comment by bsbeeks** [comment]
It should simplify the component quite a bit.

**Comment by lukeschunk** [comment]
Yeah i'm literally just making the component the list of options, and i'm going to handle it like the modal: 
```
{this.state.showSelect ? (
<Select />
) : null} 
```

**Comment by bsbeeks** [comment]
oh, that's one way to approach it. Haven't thought about doing it that way. But you would lose any global animation/positioning that'd you'd get from having the component show/hide the options itself. 

The real problem we're trying to solve is how do we re-use just the dropdown menu portion of the Select component. 

One way to approach this for backwards compatibility is to create a new component called Dropdown that contains the logic to show/hide and format the options. You'd basically be duplicating some of the logic from the Select component. The Dropdown component would have a prop called `trigger` that would allow users to pass in any string, number, or jsx. After you build that component, you could use it inside the Select component. Then the Select component would mainly be responsible for providing a pre-formatted, reusable trigger. Does that make sense?

**Comment by lukeschunk** [comment]
That does make sense - I'll look into that idea more - we did think about the global positioning issue, which might be tough to fix if I do it how I listed above^ 

Mobile is a bit different since the options always display full screen, so I think the way I listed above is the way to go there, but perhaps not for this. Another thing I want to be able to accomplish is opening and closing the select component from the parent and not just from one trigger.

**Comment by derek-boman** [comment]
@lukeschunk: you should also check with @jmophoto on this, he may have built this for a FinSmart project. Also @iheartrachie said she was working on it as part of #184.

**Comment by iheartrachie** [comment]
Talked with Luke and he's going to take this. I'm going to close #184.

**Comment by derek-boman** [comment]
@lukeschunk: any progress on this?
