### ISSUE TITLE
Button Hover Effect Could Be More Noticeable?

### ISSUE THREAD

**Issue by lukeschunk** [mxenabled/mx-react-components#187]
I was noticing that our button hover effect - especially on a medium-quality monitor is really hard to see. Perhaps we could do something to change this? Maybe increase the hue difference in the `:hover` state to be more dramatic?

**Comment by derek-boman** [comment]
@lukeschunk: I completely agree. How much are we changing the hue difference now? We could probably double it.

**Comment by lukeschunk** [comment]
It looks like we're knocking it back 8 points in each value on the RGB scale though I'm not exactly sure - @bsbeeks I'm unclear on what happens in this bit of code: `const num = parseInt(color, 16);` where we use base 16?? 

Just playing around, I think changing the `-8` to a `-25` in this:
`backgroundColor: StyleConstants.adjustColor(this.props.primaryColor, -8),` Could be a good degree of change. 

On another note, I think this could be a great issue to push out to the community - would be an awesome `first-timer-only` issue.

**Comment by derek-boman** [comment]
@lukeschunk: keep me posted on this. When the revised color goes live or if you come up with a better way of handling this than the current RGB script.

**Comment by lukeschunk** [comment]
I will keep you posted. 

I think since what we talked about this morning (knocking the number from `-8` to `-30` is a pretty simple fix I'll open a PR on that today or Monday at the latest. 

In terms of adjusting the function to handle things a bit better - that might be further down the road and perhaps is something we could push out to the community.

**Comment by bsbeeks** [comment]
@lukeschunk The second number in `parseInt` tells it to convert the number to a hexadecimal (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#Description) which is what we use for CSS colors.

The second parameter passed into `adjustColor` is the percent you want the color lightened. So `-8` would be 8% darker. `-25` would be 25% darker. 

@derek-boman I think the function we're using to lighten/darken the color is solid and fairly standard.

**Comment by lukeschunk** [comment]
Gotcha, thanks for clarifying. @bsbeeks I want to take a look at the function with you perhaps because I noticed when you pass in a -40 or -50 where the -8 currently is, the color won't change at all - is this the behavior we want?

**Comment by bsbeeks** [comment]
Hmmm, we'll have to look at it.

**Comment by derek-boman** [comment]
@lukeschunk: any update on this?

**Comment by lukeschunk** [comment]
Haven't looked at the actual function in detail yet, but did make this PR: https://github.com/mxenabled/mx-react-components/pull/191
