### ISSUE TITLE
Icon Component: Passing an array of styles to the style prop not working

### ISSUE THREAD

**Issue by cerinman** [mxenabled/mx-react-components#194]
The `propTypes` for the `style` prop in the Icon component show it as accepting either an array or an object.  If you pass it an array, the styles in the array are not applied.

**Comment by iheartrachie** [comment]
FYI, this is working in the button component where we're using the spinner icon when the button isActive. You can see the styles definition in my PR [here](https://github.com/mxenabled/mx-react-components/pull/231/files#diff-734f11edfaa69e2a96b8cb8f7f06fb6bR41).

**Comment by cerinman** [comment]
Chatted with @iheartrachie on this offline.  I wondering now if our issue internally is a radium array that ends up looking like this `[object, array]` rather than `[object, object]`.  I'll take a closer look and update this issue accordingly.  Thanks for  looking into this Rachel.
