### ISSUE TITLE
New sliding drawer component

### ISSUE THREAD

**Issue by derek-boman** [mxenabled/mx-react-components#195]
#### Overview
This pattern seeks to replace the current pattern of stacking modals within Money Desktop (which currently allows modals up to 6-levels deep!) The drawer pattern does this by opening a drawer from the right side of the screen and a scrim to partially conceal content underneath. This overlapping pattern is common in modern web design and adapts well for mobile usage.

The drawer provides enough screen real-estate for many use-cases and should be considered the go-to pattern for content secondary and tertiary to the main view

#### Levels
Once a drawer is triggered, it opens by sliding in from the right side; it can be closed using a return icon in the upper-left or by completing requested interactions (such as filling out a form). A user may also have the option to navigate to a deeper level by drilling into content, however it is recommended that this be limited to 2 levels. Additional levels should be opened when content represents a child relationship to the current context.

Minor interactions, such as splitting or excluding a transaction, should not open another level because they relate directly to existing context. In this case other design patterns should be used. While the return icon will navigate back a single level, pressing the scrim area will close the drawer regardless of current level . To help orient the user, an animation is used to indicate a change in level.

#### Sibling Content
Additionally, if the content has available siblings the users may be given the option to cycle through siblings (examples: accounts or transactions within a list). This cycling is done within the current level. Animations are used to single the state change. Note: Pressing the return icon would close the entire level, not reverse cycle through sibling content.

#### Construction
A drawer is constructed of the areas outlined below.

##### Drawer Navigation Bar
This area contains the return icon on the left side. The right side may contain sibling navigation or other navigational controls. This area does not scroll.

##### Drawer Header
This area identifies the content in the body area. It may also contain action buttons to delete, submit or otherwise edit body content. This area scrolls with body. This area is optional and will not appear in all drawer implementations.

##### Drawer Body
Contains majority of content. Lengthy content may scroll and / or may be divided using Tab pattern. Child content may trigger an additional drawer level. The body is composed of two 300px columns which are well-suited for mobile / mini adaptation. 

#### Mobile version
While the desktop version of drawer overlaps only a portion of the screen, the mobile equivalent should overlap 100% of the screen. Columns of the body area change to stack vertically. Other behaviors are the same as outlined above.

**Comment by derek-boman** [comment]
@paniclater: are we okay to close this initial cut of the drawer component? I'm opening issues for some changes to it so I want to make sure the first iteration is done.

**Comment by cerinman** [comment]
Closing this.  This Drawer component is up and working in it's v2 state.
