### ISSUE TITLE
Default Value/Validation in Select Component doesn't match.

### ISSUE THREAD

**Issue by lukeschunk** [mxenabled/mx-react-components#200]
I noticed that the PropTypes in the Select component states: `selected: React.PropTypes.object,` validating for an object. Yet in the default, it's setting the value to a boolean: 
```
getDefaultProps () {
    return {
      onChange () {},
      options: [],
      placeholderText: 'Select One',
      selected: false,
      valid: true
    };
  },
```

In the demo app, it is getting passed an object for this value... so perhaps the default value should not be a boolean?

**Comment by bsbeeks** [comment]
Good catch. We should just remove the default value all together.

**Comment by scotttball** [comment]
Close? @lukeschunk
