### ISSUE TITLE
Select Component - Multiple options appear selected/in a Hover State.

### ISSUE THREAD

**Issue by lukeschunk** [mxenabled/mx-react-components#203]
In the Select component dropdown, if you select one option, close the dropdown, then go to select another option, sometimes when the dropdown reopens, two items will have the hover state. This is better understood by viewing the screenshots below:

![screen shot 2016-03-08 at 1 59 24 pm](https://cloud.githubusercontent.com/assets/13579578/13616499/60a2b4bc-e537-11e5-9db1-16ae5abf0a78.png)
![screen shot 2016-03-08 at 1 59 38 pm](https://cloud.githubusercontent.com/assets/13579578/13616500/60a4789c-e537-11e5-9974-439624dfba05.png)

Is this worth looking into?

**Comment by bsbeeks** [comment]
This has been a known issue. If you can figure out a solution, that'd be awesome!

**Comment by lukeschunk** [comment]
Gotcha, sounds good! :crystal_ball: :+1:

**Comment by lukeschunk** [comment]
https://github.com/mxenabled/mx-react-components/pull/207
