### ISSUE TITLE
New Component / Search box 

### ISSUE THREAD

**Issue by derek-boman** [mxenabled/mx-react-components#216]
This could be a valuable component to have for searching transactions, category lists, etc. 
Stylistically it should resemble closely other form elements such as Selects and Inputs ( http://mxenabled.github.io/mx-react-components/#/components/select?_k=oc1op5).

Some specs: 
font-size: 13px
font: ProximaNovaRegular (make sure no faux bold or italics)
placeholder text color: ash
icon: search, charcoal
padding: 10px
border: 1px fog
border-radius: 2px

on focus: 
border: 1px brand color
text: charcoal

Example: 
![screen shot 2016-03-15 at 9 01 53 am](https://cloud.githubusercontent.com/assets/17180771/13782423/a2cf744c-ea8c-11e5-96c2-d35bf03f4ec5.png)

**Comment by bsbeeks** [comment]
@tumentumurchudur you've already created this component internally. When you get some time, let's move it to this repo.

**Comment by lukeschunk** [comment]
can't wait to pop this puppy :dog: into gunny

**Comment by tumentumurchudur** [comment]
@bsbeeks Yeah, I will re-format it according to the specs and move it here.

**Comment by tumentumurchudur** [comment]
@bsbeeks I just realized that `SearchInput` component has a dependency on the `Input` component which is not in the open source. Do we want to move the `Input` component here as well?

**Comment by bsbeeks** [comment]
@tumentumurchudur good question. @derek-boman we have previously discussed excluding input styles from our open source since they can differ greatly between projects and even within a project. Are we wanting to make an exception for this Search input?

**Comment by derek-boman** [comment]
@bsbeeks is it possible to have multiple input styles/types? similar to how we have multiple button styles? I've been working on simplifying this and I think I've got it down to two main types.

**Comment by bsbeeks** [comment]
depending on the styles/types we might want to just have 2 separate inputs, instead of trying to cram everything into one. Either way, it sounds like you have a solid way to move forward.

**Comment by derek-boman** [comment]
I'll finalize the spec and we can discuss how to proceed.

**Comment by derek-boman** [comment]
@tumentumurchudur is this done? can we close this?

**Comment by tumentumurchudur** [comment]
Yes, this is done. Please close.
