### ISSUE TITLE
New Pattern: Page Indicators

### ISSUE THREAD

**Issue by derek-boman** [mxenabled/mx-react-components#236]
A new UI pattern to indicate paginated slides. Useful for onboarding and first-use experiences. 

See **Components > Page Indicators** to see more detailed info: https://app.frontify.com/d/KHQZnlj1XMIO/web-patterns

![image](https://cloud.githubusercontent.com/assets/17180771/14093185/468fa49a-f509-11e5-85c5-9121feca4319.png)

![crumbs](https://cloud.githubusercontent.com/assets/17180771/14093170/28165324-f509-11e5-8e4d-da2b582233a6.png)

**Comment by lukeschunk** [comment]
When the user clicks on one of the dots, will it change the page/content?

**Comment by derek-boman** [comment]
@lukeschunk: yes.
