### ISSUE TITLE
Demo App Modal using Image that Does Not Exist

### ISSUE THREAD

**Issue by lukeschunk** [mxenabled/mx-react-components#237]
This is not a huge issue - but it could be a quick fix - let me know if there is an alternative image we can use and I'll switch it out. 

Right now the modal rendered in the demo app is referencing an imageURL that does not exist: 
` <img src='http://www.mx.com/images/home/top-t-i.png' style={[{ maxWidth: '100%', height: 'auto', margin: 'auto' }, this.state.showSmallModal && { width: 400 }]} /> `

**Comment by lukeschunk** [comment]
@bsbeeks has this been fixed or is it not a big deal?

**Comment by bsbeeks** [comment]
yep, just fixed it

**Comment by lukeschunk** [comment]
:+1:
