### ISSUE TITLE
New component / Simple Inputs

### ISSUE THREAD

**Issue by derek-boman** [mxenabled/mx-react-components#244]
We have a solid input component in place in Insight / Target that would be useful to have in the open-source. In doing so can we make sure that the component syncs up with styles for Simple Inputs from Form Elements section of Aggro style guide: https://app.frontify.com/d/KHQZnlj1XMIO/web-patterns

_From Insight / Target:_
![image](https://cloud.githubusercontent.com/assets/17180771/14257170/bb8cce76-fa59-11e5-86bd-433546dd2e6c.png)

**Comment by scotttball** [comment]
Can this be closed?

**Comment by derek-boman** [comment]
@scotttball @tumentumurchudur I'd like to see an example of this in use before we close it. Is this being used anywhere already?

**Comment by bsbeeks** [comment]
@derek-boman you can view the docs for it which include a demo: http://mxenabled.github.io/mx-react-components/#/components/simple-input

**Comment by derek-boman** [comment]
Cool. I'll check it out. Nice to see you still contributing @bsbeeks 😏
