### ISSUE TITLE
Margin Issues on Buttons with Icons

### ISSUE THREAD

**Issue by iheartrachie** [mxenabled/mx-react-components#269]
There are two button types this is affecting:
1. **Loading Button**
The spinner styles aren't being applied when the button `isActive`, causing the button height to be expanded.
![ajmbwfnwlc](https://cloud.githubusercontent.com/assets/1916697/14682816/ac1c96f0-06e4-11e6-8de3-29d305fe1026.gif)
2. **Button Groups**
The icon's negative margins `-4px -5px -3px` are okay on the demo page but docs would require `-6px -5px -3px`. How can we make sure this is consistent?
![screen shot 2016-04-20 at 10 43 34 am](https://cloud.githubusercontent.com/assets/1916697/14682838/c400258e-06e4-11e6-89dd-fb283d11b1c0.png)

Both components look fine on the demo page but not in our documentation. This may not be an issue elsewhere, we still need to investigate.
@jmophoto

**Comment by scotttball** [comment]
1. <b>Loading Button</b>
The button height is being modified because the `<Icon>` used in the animation has a fixed height on it which modifies the button height. 
2. <b>Button Groups</b>
I'll have to dig into it to figure out what the deal is with it.

**Comment by scotttball** [comment]
@iheartrachie and I spoke offline and we think that the buttons in the `gh-pages` are being affected by the parent styling and overriding some of the styling for the buttons and causing this.

**Comment by iheartrachie** [comment]
I verified this works without issue in an internal project so I'm going to agree with Scott. I'll fiddle around to see if I can find the cause. If not, I'll close this issue.

**Comment by iheartrachie** [comment]
The button group issue will be closed by #278. The loading button issue was a Radium and React 15 issue that Scott has since resolved. I'm going to go ahead and close this issue.
