### ISSUE TITLE
Drawer body revisions

### ISSUE THREAD

**Issue by derek-boman** [mxenabled/mx-react-components#274]
I've updated the Construction section of the drawer component here: https://app.frontify.com/d/KHQZnlj1XMIO/web-patterns#/components/drawer/construction

This change will allow the drawer body to be organized in 1–3 columns and includes a few extra specs for responsive layout (I'm not sure internally we will need these at MX but makes for a well rounded component in the open-source). We've recently found an inset card design makes layout clearer when using drawer tabs etc. 

![1 column](https://cloud.githubusercontent.com/assets/17180771/14801957/f446fe1e-0b0a-11e6-9323-91c89622467c.png)
![1 column small](https://cloud.githubusercontent.com/assets/17180771/14801959/f449153c-0b0a-11e6-81ff-f11d4a1801f3.png)
![2 column](https://cloud.githubusercontent.com/assets/17180771/14801958/f448f6ce-0b0a-11e6-83e5-09e82025c566.png)
![2 column small](https://cloud.githubusercontent.com/assets/17180771/14801961/f44969d8-0b0a-11e6-9ffd-ff292d0ea251.png)
![3 column](https://cloud.githubusercontent.com/assets/17180771/14801962/f4496bae-0b0a-11e6-974c-d70f0c812e4f.png)
![3 column small](https://cloud.githubusercontent.com/assets/17180771/14801960/f4493ca6-0b0a-11e6-8668-62eb92b1fa94.png)

**Comment by cerinman** [comment]
This will be managed internally when we use the Drawer component.  Closing this.  Let me know if you have questions.
