### ISSUE TITLE
Drawer header revisions

### ISSUE THREAD

**Issue by derek-boman** [mxenabled/mx-react-components#276]
I've updated the Construction section of the drawer component here: https://app.frontify.com/d/KHQZnlj1XMIO/web-patterns#/components/drawer/construction

This issue is for the header portion of the drawer (see also #274 and #275). There are two general types of drawer headers I've found a need for: one with a large amount and one with action buttons. See Aggro style guide for full specs.

![header bar 1 example](https://cloud.githubusercontent.com/assets/17180771/14802180/9236939a-0b0c-11e6-89de-f07feae4adc2.png)
![header bar 1 example copy](https://cloud.githubusercontent.com/assets/17180771/14802181/948a7f44-0b0c-11e6-9b20-0c249d0f2dca.png)

**Comment by cerinman** [comment]
This will also be an internal thing.  The OS Drawer component is just the wrapper/title bar so we can't specify this stuff here.  Closing, let me know if you have questions.

**Comment by derek-boman** [comment]
@cerinman good to know. I'd like to make sure that we build this in some kind of reusable manner since it'll be used in different places throughout the app: Transaction Details, Account Details, etc. I want to make it easy to update. From the design side, I see these two header styles as interchangeable molecules in a drawer organism. 

How do you typically handle this in the code? Can React nest components?

**Comment by cerinman** [comment]
Yes, React can nest components with no issues and yes the plan is to make those their own components to make our lives easier.
