### ISSUE TITLE
Improvements on Date Picker

### ISSUE THREAD

**Issue by iheartrachie** [mxenabled/mx-react-components#280]
Here are some things I noticed when trying to use the `DatePicker` component. I'd like feedback before I start making changes though. There may be other things that aren't working smoothly, these are just want I happened upon so far.

1. `useInputForSelectedDate` allows a user to input a value but on blur the value isn't saved or returns 'invalid date'
2. `defaultDate` overrides `placeholderText` when set. 
3. `defaultDate` should default to today. Thoughts?

**Comment by iheartrachie** [comment]
Docs should be updated to indicate that `format` actually defaults to `'MMM D, YYYY'` but it's only for display. `onDateSelect` returns a unix timestamp.

**Comment by derek-boman** [comment]
@iheartrachie: the date picker needs some new design work as well. If you're going to be working on it, I'd like to sync up on new requirements.

See docs here (scroll down a bit): https://app.frontify.com/d/KHQZnlj1XMIO/web-patterns/inputs/form-elements/select#/inputs/form-elements/select

**Comment by iheartrachie** [comment]
The internal item I'm working on right now needs a range selector. I think this is a good time to work on both of these components. I'll tackle it over the next couple of days.

**Comment by derek-boman** [comment]
Okay. LMK if you need additional design spec. I assume you mean the date range selector not this one [here](http://mxenabled.github.io/mx-react-components/#/components/range-selector?_k=9hv6le).

There are a few examples on [here](http://www.jqueryrain.com/?A_MO0kvZ) that I like from a functionality / usability standpoint (not necessarily how they're built). The date range selector in a single calendar here is really nice.

**Comment by derek-boman** [comment]
Here are some design specs I've been working with. LMK if something isn't going to work.

![simple date selector copy 2](https://cloud.githubusercontent.com/assets/17180771/14904624/a2de5118-0d66-11e6-961e-d51973501887.png)
![simple date selector copy](https://cloud.githubusercontent.com/assets/17180771/14904623/a2db5206-0d66-11e6-8cd6-ed349f02de60.png)

**Comment by iheartrachie** [comment]
Thank you for this! I thought we were doing outline on hover, not a Fog background. Let's chat tomorrow.

**Comment by iheartrachie** [comment]
Historically we had the option to allow the user to type in a date. It may have worked at one point but it's not working now. To accomplish this we need to convert the input string to a UTC timestamp. Turns out Moment.js [no longer supports](https://github.com/moment/moment/issues/1407) converting strings of this type. I can do some JS to parse the string and whatnot but wanted to check first to see if this is something we'd still like to include in the component.

**Comment by cerinman** [comment]
@iheartrachie I believe we're ok with leaving the `type a date` feature out for now.  It adds complexity and more validation that I don't feel needs to be a concern at this point based upon how we currently plan to use the component.  I'm sure we'll add this later but for now let's just go with selecting a date from the calendar.
