### ISSUE TITLE
Date Picker DefaultDate not formated

### ISSUE THREAD

**Issue by iheartrachie** [mxenabled/mx-react-components#291]
I missed this in my latest PR
![screen shot 2016-05-03 at 4 51 19 pm](https://cloud.githubusercontent.com/assets/1916697/15000759/6676e1a8-114f-11e6-9011-5e3aca449a7e.png)

At some point I must have removed the formatting for the defaultDate prop and forgot to re-add it. I'll revert the docs until I fix this.

**Comment by derek-boman** [comment]
A few additional styling things:

- [ ] date letters SMTWTFS should be `font-size: Small` (They should stay semibold though)
- [ ] The arrows should have a similar hover, a 1px Fog Border with a 2px `border-radius`, the target area should be the same size as the dates (ie the Right Arrow should perfectly align with the Saturday column and the left with the Sunday column)
- [ ] Down-Caret in the field should match size, padding etc of the standard Select menu.

![simple date selector copy](https://cloud.githubusercontent.com/assets/17180771/15050628/1a0b82ba-12b2-11e6-8833-4af8c1305fd2.png)
