### ISSUE TITLE
Modal: Add css classes to allow styling through external stylesheets

### ISSUE THREAD

**Issue by bsbeeks** [mxenabled/mx-react-components#31]
This should be a fairly straight forward change and should not effect the UI or functionality of the component. It's what we'd consider a "no harm" change. Here's what you need to do:

- [ ] Fork the repo
- [ ] run `npm install`
- [ ] run `npm run demo`. This will open up a new browser window with demos of each component. It will refresh whenever you save changes to the files in the `src` directory.
- [ ] open up `src/components/Modal`
- [ ] On line 23, add `className='mx-modal'` before the `style` prop declaration.
- [ ] On line 24, add `className='mx-modal-scrim'` before the `onClick` prop declaration.
- [ ] On line 25, add `className='mx-modal-content'` before the `style` prop declaration.
- [ ] On line 27, add `className='mx-modal-close'` on it's own line, before the `onClick` prop declaration.
- [ ] Open the demo and make sure your changes didn't break the Modal component.
- [ ] run `eslint src` to check for syntax and style errors. Fix the errors as needed.
- [ ] Commit your changes to the `src/` directory
- [ ] Push your changes to your fork
- [ ] Create a PR and include `Fixes #31` in the message
- [ ] Get merged and celebrate :tada:

**Comment by Charlotteis** [comment]
Hi @bsbeeks. I just wanted to take the time to say _thank you_ for this awesome list. It's really encouraging for me (creator of @yourfirstpr) to keep going, and I've scheduled this issue for a tweet for today at 1PM (GMT).

🙏🏼
