### ISSUE TITLE
New Category Icons

### ISSUE THREAD

**Issue by derek-boman** [mxenabled/mx-react-components#349]
New Icons to add to the set. Some of them should replace existing icons (education, cash, etc)
Download SVGs here: https://moneydesktop.box.com/s/ayc7x5j3z6jpx5zn2p5qk4jv5q5n71yt 

![screen shot 2016-06-21 at 12 50 11 pm](https://cloud.githubusercontent.com/assets/17180771/16242231/bef915e6-37ae-11e6-8d66-b7f641b5215b.png)

**Comment by lukeschunk** [comment]
there are more icons in the picture above then in the link to the files - is that intentional?

**Comment by derek-boman** [comment]
Yes, some of these shown are already in the set and are not being updated.

**Comment by lukeschunk** [comment]
@derek-boman good to close?
