### ISSUE TITLE
DonutChart: Add css classes to allow styling from external stylesheets

### ISSUE THREAD

**Issue by bsbeeks** [mxenabled/mx-react-components#36]
This should be a fairly straight forward change and should not effect the UI or functionality of the component. It's what we'd consider a "no harm" change. Here's what you need to do:

- [ ] Fork the repo
- [ ] run `npm install`
- [ ] run `npm run demo`. This will open up a new browser window with demos of each component. It will refresh whenever you save changes to the files in the `src` directory.
- [ ] open up `src/components/DonutChart`
- [ ] On line 218, add `className='mx-donutchart'` before the `style` prop declaration.
- [ ] On line 220, add `className='mx-donutchart-svg'` before the `height` prop declaration.
- [ ] On line 221, add `className='mx-donutchart-g'` before the `style` prop declaration.
- [ ] On line 189 and 200, add `className='mx-donutchart-data'` before the `onClick` prop declaration.
- [ ] On line 204, add `className='mx-donutchart-data-label'` before the `style` prop declaration.
- [ ] On line 201, add `className='mx-donutchart-data-value'` before the `style` prop declaration.
- [ ] Open the demo and make sure your changes didn't break the DonutChart component.
- [ ] run `eslint src` to check for syntax and style errors. Fix the errors as needed.
- [ ] Commit your changes to the `src/` directory
- [ ] Push your changes to your fork
- [ ] Create a PR and include `Fixes #36` in the message
- [ ] Get merged and celebrate :tada:

**Comment by SharonRogers** [comment]
Just had a question on this open component. I am a recent graduate from DevMountain and am excited for the opportunity. The instructions starting at line 193 and 204 do not match the lines in the code. Line 193 is an else statement and does not have an onclick property. Also there seems to be an error possibly on line 180 but I could be mistaken. It appears to not close properly which may be impacting something else. I am not able to get the demo to run. Would love to participate but not sure how to proceed with these conflicts. Thanks.

**Comment by bsbeeks** [comment]
@SharonRogers thanks for the feedback. Someone from our team will take a look today and get back to you.

**Comment by jmophoto** [comment]
@SharonRogers  - thanks for your questions and willingness to contribute! You were right about the line numbers being off. I have updated the instructions, so they should match up now.

As for the item on line 180, since the <circle> attribute does not have any children, you can use a self-closing attribute. We use line breaks when an attribute has three or more params just to make it more readable. In effect this could be written as
```javascript
<circle alltheparams></circle>
```

Feel free to reach out if you have any other questions.

**Comment by SharonRogers** [comment]
One other question and I am ready to submit. Sorry I have taken so long. I can't seem to get the demo to run so I am not able to check on it. Any advice? Thanks!

**Comment by bsbeeks** [comment]
What happens when you run `npm run demo`?

**Comment by SharonRogers** [comment]
It takes me to the browser but nothing shows up. there is one error that is in the dev tools

Uncaught TypeError: React.initializeTouchEvents is not a function

So I am not sure if this is the issue. Thanks for the help.

**Comment by bsbeeks** [comment]
Try running 'npm install'

**Comment by SharonRogers** [comment]
I did run it and then the demo and it still does not open anything. I will try some other things on my end. Thank you for your help.

**Comment by bsbeeks** [comment]
Hmmm, we're not able to duplicate the issue on our end. Have you pulled down master recently?

**Comment by jmophoto** [comment]
On other projects, I have deleted the node_modules directory and then performed a new npm install. Sometimes this helps.

**Comment by danguilherme** [comment]
The project is running with no errors here. Here's exactly what I did:
* `git clone https://github.com/mxenabled/mx-react-components.git`
* `cd mx-react-components`
* `npm install`
* `npm run demo`

Demo did not run at first, the task only caused webpack to run:
![npm-run-demo](https://cloud.githubusercontent.com/assets/1488378/10556462/ee6ed658-7459-11e5-91fb-a764427ed6b2.png)

Running `node demo\server.js` caused the demo to run normally, with no errors:
![running](https://cloud.githubusercontent.com/assets/1488378/10556500/d468616a-745a-11e5-8144-622a489459f5.png)

I am on Windows 10, Chrome 45, Node 0.12.3 (if that makes any difference).
