### ISSUE TITLE
Make all components responsive

### ISSUE THREAD

**Issue by iheartrachie** [mxenabled/mx-react-components#363]
The following components need to be made responsive:

- [ ] BarChart
- [x] DateRangePicker (priority) - Tommy
- [x] DateTimePicker (https://github.com/mxenabled/mx-react-components/pull/367)
- [x] DisplayInput (Dan)
- [ ] TimeBasedLineChart
- [x] Drawer (#361)

**Comment by derek-boman** [comment]
Are more of these done? I've seen some updates to the drawer and barchart. Is there more to do there still before we can check those off?

**Comment by iheartrachie** [comment]
I think for now these are good.
