### ISSUE TITLE
Display Input / Responsive Revisions

### ISSUE THREAD

**Issue by derek-boman** [mxenabled/mx-react-components#373]
The Display Input component has some problems adapting to small screens. This should also set some patterns how other Display Menus (date picker, category selectors, tag lists, etc) behave to add consistency to forms and "Details" pages.

**Current "Transaction Details" page on mobile:**
![screen shot 2016-07-13 at 10 57 41 am](https://cloud.githubusercontent.com/assets/17180771/16812186/3b1ab81e-48e9-11e6-911c-15b267917482.png)

**Prototype "Transaction Details" with revisions:**
Mobile: https://marvelapp.com/3ag56fe#13715726
Desktop: https://marvelapp.com/hfji73#13772514

**Frontify spec:** https://app.frontify.com/d/KHQZnlj1XMIO/web-patterns#/inputs/form-elements/input

**New Design:**
![display inputs](https://cloud.githubusercontent.com/assets/17180771/16812887/62243568-48ec-11e6-8f66-527c47de4962.png)
![display input - mobile](https://cloud.githubusercontent.com/assets/17180771/16812892/674d6000-48ec-11e6-8155-ed244080b8f2.png)

**Construction**
![input construction](https://cloud.githubusercontent.com/assets/17180771/16812898/6c8107ca-48ec-11e6-8d7e-f94aff9c5e7b.png)
![input construction - mobile](https://cloud.githubusercontent.com/assets/17180771/16812899/70759080-48ec-11e6-9563-4d51206db9f7.png)

**Comment by vintagepenguin** [comment]
- [ ] Responsive 
- [ ] Refactor Validations

**Comment by derek-boman** [comment]
Here are some additional specs.

![typography](https://cloud.githubusercontent.com/assets/17180771/17229930/0c7b2f58-54d7-11e6-9be9-693db843c877.png)
![padding](https://cloud.githubusercontent.com/assets/17180771/17229931/0c7e2050-54d7-11e6-96bc-6307588e1da3.png)
![padding - mobile](https://cloud.githubusercontent.com/assets/17180771/17229929/0c7ab1f4-54d7-11e6-8722-d645d198a657.png)

**Comment by vintagepenguin** [comment]
Closing this since Tommy's PR resolved it 👍

**Comment by derek-boman** [comment]
@vintagepenguin: can we close this then?
