### ISSUE TITLE
RangeSelector: Add css classes to allow styling from external stylesheets

### ISSUE THREAD

**Issue by bsbeeks** [mxenabled/mx-react-components#38]
This should be a fairly straight forward change and should not effect the UI or functionality of the component. It's what we'd consider a "no harm" change. Here's what you need to do:

- [ ] Fork the repo
- [ ] run `npm install`
- [ ] run `npm run demo`. This will open up a new browser window with demos of each component. It will refresh whenever you save changes to the files in the `src` directory.
- [ ] open up `src/components/RangeSelector`
- [ ] On line 275, add `className='mx-rangeselector'` before the `style` prop declaration.
- [ ] On line 276, add `className='mx-rangeselector-presets'` before the `style` prop declaration.
- [ ] On line 279, add `className='mx-rangeselector-preset'` before the `key` prop declaration.
- [ ] On line 284, add `className='mx-rangeselector-preset'` before the `onClick` prop declaration.
- [ ] On line 288, add `className='mx-rangeselector-range'` on it's own line before the `onMouseLeave` prop declaration.
- [ ] On line 296, add `className='mx-rangeselector-toggle'` before the `onClick` prop declaration.
- [ ] On line 297, add `className='mx-rangeselector-track'` before the `style` prop declaration.
- [ ] On line 298, add `className='mx-rangeselector-selected'` before the `style` prop declaration.
- [ ] On line 299, add `className='mx-rangeselector-selected-label'` before the `style` prop declaration.
- [ ] On line 303, add `className='mx-rangeselector-lower-toggle'` on it's own line before the `onMouseDown` prop declaration.
- [ ] On line 310, add `className='mx-rangeselector-lower-toggle-label'` before the `style` prop declaration.
- [ ] On line 314, add `className='mx-rangeselector-upper-toggle'` on it's own line before the `onMouseDown` prop declaration.
- [ ] On line 321, add `className='mx-rangeselector-upper-toggle-label'` before the `style` prop declaration.
- [ ] Open the demo and make sure your changes didn't break the RangeSelector component.
- [ ] run `eslint src` to check for syntax and style errors. Fix the errors as needed.
- [ ] Commit your changes to the `src/` directory
- [ ] Push your changes to your fork
- [ ] Create a PR and include `Fixes #38` in the message
- [ ] Get merged and celebrate :tada:

**Comment by tegon** [comment]
I've added a PR for this: https://github.com/mxenabled/mx-react-components/pull/54
