### ISSUE TITLE
Loader: Add css classes to allow styling through external stylesheets

### ISSUE THREAD

**Issue by bsbeeks** [mxenabled/mx-react-components#4]
This should be a fairly straight forward change and should not effect the UI or functionality of the component. It's what we'd consider a "no harm" change. Here's what you need to do:

- [ ] Fork the repo
- [ ] run `npm install`
- [ ] run `npm run demo`. This will open up a new browser window with demos of each component. It will refresh whenever you save changes to the files in the `src` directory.
- [ ] open up `src/components/Loader`
- [ ] On line 69, add `className='mx-loader'` before the `style` prop declaration.
- [ ] On line 70, add `className='mx-loader-content'` before the `style` prop declaration.
- [ ] On line 77, add `className='mx-loader-text'` before the `style` prop declaration.
- [ ] Open the demo and make sure your changes didn't break the Loader component.
- [ ] run `eslint src` to check for syntax and style errors. Fix the errors as needed.
- [ ] Commit your changes to the `src/` directory
- [ ] Push your changes to your fork
- [ ] Create a PR and include `Fixes #4` in the message
- [ ] Get merged and celebrate :tada:

**Comment by kentcdodds** [comment]
Hi! See [this](https://gist.github.com/kentcdodds/78fa2032bc5c81f81c51) :-) (same as the other comment on the other issue).
