### ISSUE TITLE
Date Picker Button not Consistent with standard buttons

### ISSUE THREAD

**Issue by lukeschunk** [mxenabled/mx-react-components#401]
The standard button has a total height of 30px:

![screen shot 2016-08-09 at 6 07 54 pm](https://cloud.githubusercontent.com/assets/13579578/17537744/5643fb54-5e5c-11e6-99f8-988a2a54c1ec.png)

The DatePicker has a total height of 40px: 

![screen shot 2016-08-09 at 6 08 09 pm](https://cloud.githubusercontent.com/assets/13579578/17537750/61fc1292-5e5c-11e6-8851-506347b6d11f.png)

@derek-boman noticed that some of our action bars in the rewrite were a little tall; the datepicker and thus action bar should be the same height as the buttons, 30px.

**Comment by lukeschunk** [comment]
also: if we were to change the datepicker height, would it break in other places?

**Comment by paniclater** [comment]
This does seem to walk the line of what is / isn't a breaking change. Since we're trying to be more inviting to others to use it, I recommend we treat it as a breaking change. I'd rather have them upgrade then deal with their CSS needing to be updated because we changed the size.

**Comment by lukeschunk** [comment]
cool 🆒 😎 🔮  I will make these changes and we can do a breaking change? orrrrr I can look into doing an NPM release candidate

**Comment by paniclater** [comment]
Either way works.

**Comment by derek-boman** [comment]
Nice to see this moving forward.

**Comment by lukeschunk** [comment]
I talked to @cerinman about this and we're going to do a quick fix and override in the mobile widgets, but at this moment we don't want to release this as a breaking change or go through the effort of figuring out our pre release pattern. Will circle back and do the actual fix in a couple of weeks though.

**Comment by cerinman** [comment]
No longer an issue.  Closing.
