### ISSUE TITLE
Modal Component updates

### ISSUE THREAD

**Issue by derek-boman** [mxenabled/mx-react-components#404]
The drawer component is now doing a lot of what the modal component was designed to do. Modal implementations requiring a header and footer should all consider switching to drawers or separate pages.

The Pattern Library has been updated with new guidelines for appropriate modal elements and design specs. Please review this documentation and make any updates needed at the OS component level (width, shadow, etc).

![image](https://cloud.githubusercontent.com/assets/17180771/17627034/f30aa2be-606c-11e6-9514-1d5435057293.png)

https://app.frontify.com/d/KHQZnlj1XMIO/web-patterns#/components/modals

**Comment by cerinman** [comment]
Modal is up to date.  Closing.
