### ISSUE TITLE
Update components affected by the new elementProps

### ISSUE THREAD

**Issue by jtanner** [mxenabled/mx-react-components#438]
We need to update a number of components after the introduction of `elementProps` in #426. I did a quick search for `Icon` and found some components that need to be updated with the new pattern, the same should be done to find uses of the other components that need to be updated:
- [ ] `DisplayInput`
- [ ] `Icon`
  - [x] src/components/Calendar.js
  - [x] src/components/DatePickerFullScreen.js
  - [x] src/components/TypeAhead.js
- [ ] `RajaIcon`
- [ ] `SimpleInput`

**Comment by lukeschunk** [comment]
Just ran through these again and this should be all fixed in the OS
