### ISSUE TITLE
Search Input / Polish

### ISSUE THREAD

**Issue by derek-boman** [mxenabled/mx-react-components#442]
A few items to tighten up on the Search Input component (or could this just use the Simple Input with a couple additional props?)

![image](https://cloud.githubusercontent.com/assets/17180771/18652125/fbb4d766-7e8c-11e6-8582-c34d5af6eaf5.png)

- [ ] Reset field icon on the right side. `icon: close-solid, fog.
- [ ] Set default font size to Medium
- [ ] Typing text is currently rgb(0,0,0) this should be Charcoal
- [ ] increase `padding-right` on the Search icon from 5px to 7px

**Comment by lukeschunk** [comment]
Do you want the reset field icon on all simple inputs or just the search input. The search input uses the simple input, and wraps it with a couple of additional things.

**Comment by derek-boman** [comment]
I think this is done. Closing.
