### ISSUE TITLE
Remove Direct Calls to PropTypes

### ISSUE THREAD

**Issue by paniclater** [mxenabled/mx-react-components#455]
In React 16 all calls to PropTypes will be stripped in producation. This means that usages other than `Component.propTypes = {}` will break with React 16.

https://facebook.github.io/react/warnings/dont-call-proptypes.html

**Comment by iheartrachie** [comment]
Are you seeing this anywhere in particular? I'm not seeing any warnings and skimming the project I don't see any place we are calling `propTypes` directly.

**Comment by cerinman** [comment]
This has been resolved.  Closing.
