### ISSUE TITLE
New Component / Needle

### ISSUE THREAD

**Issue by derek-boman** [mxenabled/mx-react-components#460]
The Needle is a new component used to indicate a UI element the user should interact with next. An example use case would be: a first-time user coming to a Goals app but hasn't added any goals yet.

**A few requirements:**
1. It is not clickable itself but should point to something that is.  
2. The Needle subtly bounces up and down (or side-to-side, depending on its orientation). It moves 10px from its starting position with a easing-curve of `cubic-bezier(0.6, -0.5, 0.2, 1.5)`
3. Color default should be `BANANA`.
4. Developer should be able to set the orientation.

**SVG File:** 
https://moneydesktop.box.com/s/vmzj8daauvwqg3a8xx3azz6l1vauel05

**Example:**
![needle_example](https://cloud.githubusercontent.com/assets/17180771/19569126/cd3c4c88-96b1-11e6-8e71-e5f679485a8e.gif)

**Comment by jtanner** [comment]
Will this be separate from or part of an on-boarding tour?

**Comment by derek-boman** [comment]
The current application is in an onboarding tour but I wouldn't want to limit it to just that.

**Comment by Maxnelson997** [comment]
First time contributing to this repo. I'll start with this.

**Comment by derek-boman** [comment]
Thanks @Maxnelson997 for your help. Happy to have you here. I don't mean to rush you but we have a fairly urgent need for this, when do you think you might have something?

**Comment by Maxnelson997** [comment]
It's pretty much done, I did it last night. Though this is my very first react component and all my finals are on Monday and Tuesday. So I will most likely have it done Wednesday.

**Comment by derek-boman** [comment]
Thanks for the update. Can't wait to see it. We appreciate your contribution.

**Comment by paniclater** [comment]
@Maxnelson997 So excited to see you contributing! Please hit me up here or on the UtahJS slack if you have questions!

**Comment by Maxnelson997** [comment]
Click the picture, it's a video of the component. This is the desired functionality correct?
[![MX Needle](https://cloud.githubusercontent.com/assets/18063554/21040040/76893184-bd9f-11e6-9fa3-e78a78e8b775.png)](https://youtu.be/IDTE3_btlwI "MX Needle")

**Comment by cerinman** [comment]
This has been finished.  Closing.
