### ISSUE TITLE
Tabs Refactor - Composability & Reusability 

### ISSUE THREAD

**Issue by lukeschunk** [mxenabled/mx-react-components#480]
Our `<Tabs />` Component could benefit from a rewrite/refactor. 

Right now we have several cases internally where the tabs do not necessarily work with a given use case which causes us to have to create one-off tab-like components. We should be able to use our tabs for all/most use cases. 

What needs to be done I think is more composability, and perhaps two components a `<Tabs>` and an individual `<Tab>`. I have done a bit of research on this but will add to this issue if need be.

**Comment by derek-boman** [comment]
@jtanner has expressed interest in working on this recently. Here's some updated spec: https://company-23585.frontify.com/document/46684#/components/tabs

**Comment by jtanner** [comment]
@derek-boman I created a new issue for adding the "pill" tab type: https://github.com/mxenabled/mx-react-components/issues/567

**Comment by cerinman** [comment]
This has been completed.  Closing.
