### ISSUE TITLE
New icons / Boxes & Radios

### ISSUE THREAD

**Issue by derek-boman** [mxenabled/mx-react-components#485]
Some new icons to add to our set. This is for creating checkboxes and radio button components.

[box-icons.zip](https://github.com/mxenabled/mx-react-components/files/657917/box-icons.zip)

![image](https://cloud.githubusercontent.com/assets/17180771/21273248/e2e656f0-c37f-11e6-88a5-c485457be52f.png)
![image](https://cloud.githubusercontent.com/assets/17180771/21273256/e8cb64ca-c37f-11e6-98ce-6a629777371c.png)

**Comment by redperk** [comment]
These have been added to the icon list. Thanks @derek-boman!
