### ISSUE TITLE
New Component / Message Box

### ISSUE THREAD

**Issue by derek-boman** [mxenabled/mx-react-components#487]
This component will allow for messaging to the user for information, errors, or warnings.

![info medium](https://cloud.githubusercontent.com/assets/17180771/21698644/21ad0e62-d355-11e6-9c0f-7a29d29292d0.png)
![warning mobile](https://cloud.githubusercontent.com/assets/17180771/21698626/09199348-d355-11e6-8eb4-f44bd882c417.png)

Here's the spec: https://app.frontify.com/d/KHQZnlj1XMIO/web-patterns#/general/messaging

**Comment by lukeschunk** [comment]
we have this component now - closing
