### ISSUE TITLE
import all mx react components

### ISSUE THREAD

**Issue by mrhaxic** [mxenabled/mx-react-components#524]
Hi guys how can i import and use mx-react-components after installed by npm

this is the original code (App.js)

import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

```
class App extends Component {
  render() {
    return (
      <div className="App">
        <div className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h2>Welcome to React</h2>
        </div>
        <p className="App-intro">
          To Oka started, edit <code>src/App.js</code> and save to reload.
        </p>
      </div>
    );
  }
}

export default App;
```

**Comment by jmophoto** [comment]
You should be able to add this:
`import { Button, Icon } from 'mx-react-components';`

And then in your render
`<Button type='primary' />`
and 
`<Icon type='attention' />`

**Comment by mrhaxic** [comment]
@jmophoto it is working fine, is there a line to import all components ?

**Comment by jmophoto** [comment]
The mx-react-components is designed more as a central location for individual components as opposed to a library to be imported all at once.

**Comment by mrhaxic** [comment]
@jmophoto Appreciate.
