### ISSUE TITLE
Responsive spacing

### ISSUE THREAD

**Issue by derek-boman** [mxenabled/mx-react-components#525]
I've seen a need for this in our component system for quite a while now. This issue is for us to come up with a standardized way of uses different spacing constants depending on the viewport size.

A common use case for this would be to wrap content in the Drawer component with `LARGE` spacing on M and L breakpoints and `SMALL` on mobile screens. 

![responsive spacing - desktop](https://cloud.githubusercontent.com/assets/17180771/23682956/9d4535bc-0353-11e7-96c9-133900d5b2cf.png)

**Comment by cerinman** [comment]
This has been solved internally with our DrawerCard component I believe and we've had no traction here.  Closing.
