### ISSUE TITLE
Flexbox and Columns

### ISSUE THREAD

**Issue by iheartrachie** [mxenabled/mx-react-components#538]
I've noticed that Columns don't play too well with flexbox because it adds a bunch of divs between styled parents and the children of the Column. Since we aren't currently passing a styles prop, extra JSX is needed for flexbox to work. Below is an example of how I've worked around this issue but I wanted to open a discussion to explore all our options.

### Example Problem
```
<div style={{ display: 'flex' }}>
  <Column span={...}>
    <div style={{ alignSelf='center' }}>
      I should be centered but I'm not :(
    </div>
  </Column>
  <div style={{ alignSelf='center' }}>
    ...
  </div>
</div>
```

### Example Workaround
```
<div style={{ display: 'flex' }}>
  <Column span={...}>
    <div style={{ display: 'flex' }}>
      <div style={{ alignSelf='center' }}>
        Oh good I'm centered now \o/
      </div>
    </div>
  </Column>
  <div style={{ alignSelf='center' }}>
    ...
  </div>
</div>
```

**Comment by jtanner** [comment]
Can you show an example of how you would like it to work?

**Comment by paniclater** [comment]
I think I see the problem, but I'm not sure I like the idea of an outside div styled with flex being able to rearrange columns or their content.

I could see adding a prop to the Column component that would allow for the display property to be configured to flex?

I feel like adding a styles prop is just too powerful and will be abused.

**Comment by iheartrachie** [comment]
@jtanner I'm not sure yet. I agree with Ryan in that a styles prop may be too powerful. Maybe we could pass a flex flag of sorts and apply that to the div that's directly above the children? I think that's all that would be needed to fix these flexbox bugs.

I know @phantomxc has removed the `Column` component in some places and opted for just flexbox so that may be a possibility too.

**Comment by cerinman** [comment]
This issue is out of date and has had no traction.  Closing.
