### ISSUE TITLE
MessageBox - use <h> tag for accessibility?

### ISSUE THREAD

**Issue by lukeschunk** [mxenabled/mx-react-components#546]
I think there is a good argument to be made that the `<MessageBox />` should use an `<h>` tag for its title. The trick is determining what tag should be used. In some cases the message box title might be high up in the page hierarchy and thus an `<h1>` or `<h2>` would be appropriate, but in other examples (like screenshot below) it would probably need to be an `<h3>` or `<h4>`. 

Would be interested to get some ideas on how to handle this. Passing a prop seems over-complicated. 

![screen shot 2017-04-17 at 2 32 47 pm](https://cloud.githubusercontent.com/assets/13579578/25103848/2c2fa7d4-237b-11e7-8984-5012b4bb12b6.png)

**Comment by daveguymon** [comment]
Would it be possible to use a ternary operator with an element locator (such as a className) to accomplish this, @lukeschunk?

**Comment by lukeschunk** [comment]
Possibly - the trick with this issue is the component needs to "know" about it's parent environment. I think one possible way to handle this would be to pass another component and use `this.props.children` so the developer can pick what `<h>` tag to use in the title. 

This idea isn't fully fleshed out but just what I'm thinking off the top of my head.

**Comment by cerinman** [comment]
Closing this as it is no longer relevant because of #754
