### ISSUE TITLE
Add *ref to components that can be focused etc.

### ISSUE THREAD

**Issue by jtanner** [mxenabled/mx-react-components#581]
Recently I was trying to focus a `Button` component while trying to improve the accessibility of another component and found that I couldn't focus it without updating the component. Ultimately I followed the suggestion in https://facebook.github.io/react/docs/refs-and-the-dom.html#exposing-dom-refs-to-parent-components to add a `buttonRef` prop which solved the issue nicely (thanks @phantomxc for finding the article).

I think we should make our other components that can be focused etc. more user friendly by adding a similar prop. Here's a list of components so we can keep track of which have been updated:

- [x] Button #584 
- [x] Date Picker
- [x] Date Picker Full Screen
- [x] Date Range Picker
- [x] Date Time Picker
- [x] Display Input
- [x] File Upload
- [x] Radio Button
- [x] Range Selector
- [x] Search Input
- [x] Select
- [x] Select Full Screen
- [x] Simple Input
- [x] Simple Select
- [x] Simple Slider
- [x] TextArea
- [x] Toggle Switch
- [x] Type Ahead

**Comment by markstewy** [comment]
@jtanner Do we simply need a ref={this.props.myComponentNameRef} added to the **_parent div_** of each of these components along with a new proptype to match? 

Or do some components need multiple refs nested within? 

I've never contributed to open source before, but I would like to become a regular if there is any way I can add value.

**Comment by jtanner** [comment]
@markstewy yes, similar to #584.

We'd love the help if you want to contribute ❤️

**Comment by jtanner** [comment]
Completed with #699
