### ISSUE TITLE
Keep documentation example code in sync with the live demo

### ISSUE THREAD

**Issue by jtanner** [mxenabled/mx-react-components#582]
I had a chat with @jmophoto recently about how our documentation example code has a tendency to get out of sync with the code used for the demo. Using the same code for both the demo and the example I think would help. Here's an idea for how we could accomplish sharing the code:

1. Move the demo code in the docs files to a separate file. For example, documentation markup for `Tabs` would be in `TabsDocs.js` and it would require the demo component `TabsDemo.js`.
2. Add [webpack raw-loader](https://github.com/webpack-contrib/raw-loader) so we can use to load a file as a string.
3. Require the demo code as a string using `'raw-loader!./TabsDemo.js'` in `TabsDocs.js`
4. Add a `Show source` button below the demo to show the code (instead of showing it at the bottom of the file)

#### Picture example:
![screen shot 2017-05-25 at 10 23 41 am](https://cloud.githubusercontent.com/assets/4348/26460439/da5281a0-4136-11e7-9abc-cadbe8e33f06.png)

#### Then when clicked:
![screen shot 2017-05-25 at 10 23 41 am](https://cloud.githubusercontent.com/assets/4348/26460439/da5281a0-4136-11e7-9abc-cadbe8e33f06.png)
![screen shot 2017-05-25 at 10 24 17 am](https://cloud.githubusercontent.com/assets/4348/26460445/dd11829c-4136-11e7-830f-13346c670dbe.png)

**Comment by paniclater** [comment]
I think this would be super cool.
