### ISSUE TITLE
Manage FocusTrap for when multiple Drawers are open

### ISSUE THREAD

**Issue by jtanner** [mxenabled/mx-react-components#585]
@lukeschunk pointed out that when a drawer is opened on top of another drawer and then closed, the focus is no longer trapped on the first drawer.

We need a way to manage what on the page is currently focus trapped and [pause/unpause](https://github.com/davidtheclark/focus-trap#focustrappause) the other traps.

[Demo 6](https://github.com/davidtheclark/focus-trap/blob/master/demo/js/demo-six.js) is an example of managing the traps.

**Comment by cerinman** [comment]
Haha nice, I hadn't even seen this issue when I started working on a fix.  Thanks for pointing it out @jtanner
