### ISSUE TITLE
Support a second path in icons to allow for background colors

### ISSUE THREAD

**Issue by iheartrachie** [mxenabled/mx-react-components#638]
Some of our icons have versions that have a colored circle but a transparent icon in the middle. This is okay most of the time but doesn't work when the icon is placed above another element. A good example is `attention-solid` used as a flag on the corner of institution logos.

![screen shot 2017-07-24 at 2 06 33 pm](https://user-images.githubusercontent.com/1916697/28542429-5437f952-7079-11e7-95b2-c1147a4b98c5.png)

Adding a background doesn't work because the wrapping div is not always the same size as the icon. Laying a div behind the svg is fragile and difficult to support responsibly. Adding a second path to customize via props will give us the flexibility we need while maintaining the current set of icons.

**Comment by cerinman** [comment]
This will be resolved with https://github.com/mxenabled/mx-react-components/pull/777 in release 2.2.25.  Closing.
