### ISSUE TITLE
Calendar Component Navigable By Keyboard 

### ISSUE THREAD

**Issue by lukeschunk** [mxenabled/mx-react-components#689]
In order to be accessible, the Calendar component needs to be navigable by the keyboard. We did something similar in the `<DateRangePicker />` month table, see this file: https://github.com/mxenabled/mx-react-components/blob/master/src/components/DateRangePicker/MonthTable.js 

You'll notice that in the `DateRangePicker` the calendar is navigable by using the arrow keys and enter keys, whereas in the `Calendar` component it is not. 

![screen shot 2017-12-19 at 10 08 33 am](https://user-images.githubusercontent.com/13579578/34169523-e74ccdf4-e4a4-11e7-8cb3-125c57c78d0c.png)

**Comment by markstewy** [comment]
@lukeschunk it looks like  <Calendar /> already has a _handleDayKeyDown method to handle arrow and enter keys  (used in both the <DatePicker /> and <DateTimePicker />). However clicking the left back arrow doesn't work in <DatePicker /> and <DateTimePicker /> will close prematurely if the fwd or back arrows are clicked. 

Should we just use this issue to address those bugs? or should I open a new separate issue?

**Comment by lukeschunk** [comment]
let's open a separate issue. I'll look into the bugs you mentioned too - I think I addressed this in the calendar and forgot to close this issue.

**Comment by markstewy** [comment]
will do! could we also close #581 and #616 ? Those fixes were merged this week.
