### ISSUE TITLE
Drawer Component > closeOnScrimClick

### ISSUE THREAD

**Issue by redperk** [mxenabled/mx-react-components#708]
So we have a boolean check to decide whether or not clicking the scrim will close the drawer.
`<div onClick={this.props.closeOnScrimClick && this.close} style={styles.scrim} />`

`onClick` is expecting a function, which is all good and fine if `closeOnScrimClick === true`, but if it's false `onClick` receives a boolean instead of a function and we get an annoying console warning:

![image](https://user-images.githubusercontent.com/6424668/36876884-839f49f4-1d74-11e8-8531-0f38d3d2ab31.png)

**Comment by cerinman** [comment]
This has been resolved.  Closing.
