### ISSUE TITLE
DatePicker Component: Fix CSS Warning Unsupported CSS Value "normal"

### ISSUE THREAD

**Issue by cerinman** [mxenabled/mx-react-components#77]
Seeing this warning when running the demo app.  `Unsupported CSS value "normal" for property "textTransform" in component "DatePicker"`

**Comment by bsbeeks** [comment]
`normal` isn't a valid value for `textTransform`. It should be `none`

**Comment by cerinman** [comment]
Might be a good first timer bug to fix.

**Comment by bsbeeks** [comment]
@cerinman can you put together steps to complete this issue and mark it as `first-timers-only`?

**Comment by cerinman** [comment]
yep, will do.

**Comment by cerinman** [comment]
Instructions for fixing bug:

- [ ] Fork the repo
- [ ] run `npm install`
- [ ] run `npm run demo`. This will open up a new browser window with demos of each component. It will refresh whenever you save changes to the files in the `src` directory.
- [ ] open up `src/components/DatePicker.js`
- [ ] On `line 341` change `textTransform: 'normal'` to `textTransform: 'none'`.  Link for reference: https://github.com/mxenabled/mx-react-components/blob/master/src/components/DatePicker.js#L341
- [ ] Open the demo and make sure your changes didn't break the DatePicker component.
- [ ] run `eslint src` to check for syntax and style errors. Fix the errors as needed.
- [ ] Commit your changes to the `src/` directory
- [ ] Push your changes to your fork
- [ ] Create a PR and include `Fixes #77` in the message
- [ ] Get merged and celebrate :tada:
